# Generated by Django 4.2.16 on 2024-11-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='tipo',
            field=models.CharField(choices=[('Cardio', 'Cardio'), ('Fuerza', 'Fuerza'), ('Yoga', 'Yoga'), ('Pilates', 'Pilates'), ('Correr', 'Correr'), ('Natación', 'Natación'), ('Ciclismo', 'Ciclismo'), ('Baile', 'Baile'), ('Fútbol', 'Fútbol'), ('Basquetbol', 'Basquetbol'), ('Tenis', 'Tenis'), ('Entrenamiento funcional', 'Entrenamiento funcional'), ('Escalada', 'Escalada'), ('Boxeo', 'Boxeo'), ('Artes marciales', 'Artes marciales')], max_length=50),
        ),
    ]
