# Generated by Django 4.2.16 on 2024-11-17 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='duracion',
        ),
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.TextField(default='Sin descripción'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_backend', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(default='Sin descripción')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('objetivo', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_backend', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grafico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('valor', models.FloatField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graficos_backend', to='actividades.actividad')),
            ],
        ),
    ]
