# Generated by Django 4.2.16 on 2024-11-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_remove_actividad_duracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='duracion',
            field=models.IntegerField(default=30),
        ),
    ]
